src/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts', include('django.contrib.auth.urls')),
    path('', include('post.urls', namespace='post')),
]

src/post/urls.py
from django.urls import path, include
from post import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'post'

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('nuevo', views.NuevoUser.as_view(), name='nuevousuario'),
    path('<slug>/', views.PostDetail.as_view(), name='detail'),
    path('create', views.CreatePost.as_view(), name='createpost'),
    path('update/<int:pk>', views.UpdatePost.as_view(), name='updatepost'),
    path('delete/<int:pk>', views.DeletePost.as_view(), name='deletepost'),
    path('like/<slug>', views.LikeView.as_view(), name='like'),
    path('sobremi', views.sobre_mi.as_view(), name='sobremi')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/post/models.py
from urllib import request
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    thumbnail = models.ImageField()
    publish_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:detail', kwargs={'slug':self.slug})

    def get_like_url(self):
        return reverse('post:like', kwargs={'slug':self.slug})

    @property
    def comment(self):
        return self.coment_set.all()

    @property
    def get_like_count(self):
        return self.like_set.all().count()

    @property
    def get_view_count(self):
        return self.vistas_set.all().count()

    @property
    def get_comment_count(self):
        return self.coment_set.all().count()

class Coment(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    coment = models.TextField()

    def __str__(self):
        return self.usuario.username

class Like(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario.username

class Vistas(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.usuario.username

src/post/forms.py
from django import forms
from post import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistroForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'email',
        ]
        labels = {
            'username': 'Nombre de usuario',
            'email': 'Correo electronico',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Coment
        fields = ('coment',)

class CreateForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = [
            'thumbnail',
            'title',
            'content',
            'slug',
            'autor',
        ]

src/post/views.py
from locale import format_string
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.urls import reverse_lazy
from post import forms, models
from django.views import generic
from django.shortcuts import get_object_or_404, redirect, render, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class PostList(generic.ListView):
    model = models.Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title_pg'] = 'Lista de Post'
        return context

class PostDetail(generic.DetailView):
    model = models.Post

    def get_object(self, **kwargs):
        object = super().get_object(**kwargs)
        if self.request.user.is_authenticated:
            models.Vistas.objects.get_or_create(usuario=self.request.user, post=object)
        return object

    def post(self, *args, **kwargs):
        form = forms.CommentForm(self.request.POST)
        if form.is_valid():
            post = self.get_object()
            coment = form.instance
            coment.usuario = self.request.user
            coment.post = post
            form.save()
            return redirect('post:detail', slug=post.slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.CommentForm()
        context['button'] = 'Comentar'
        return context

class CreatePost(generic.CreateView):
    model = models.Post
    form_class = forms.CreateForm
    success_url = reverse_lazy('post:home')

    """
    def get_success_url(self):
        return reverse('post:home')
    """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["view_type"] = 'Crear'
        return context

class UpdatePost(generic.UpdateView):
    model = models.Post
    form_class = forms.CreateForm
    success_url = reverse_lazy('post:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["view_type"] = 'Editar'
        return context

class DeletePost(generic.DeleteView):
    model = models.Post
    success_url = reverse_lazy('post:home')

class NuevoUser(generic.CreateView):
    model = User
    template_name = 'registro.html'
    form_class = forms.RegistroForm
    success_url = reverse_lazy('login')
    
class LikeView(generic.View):
    def get(self, request, slug, *args, **kwargs):
        post = get_object_or_404(models.Post, slug=slug)
        like_qs = models.Like.objects.filter(usuario=self.request.user, post=post)
        if like_qs.exists():
            like_qs[0].delete()
            return redirect('post:detail', slug)
        else:
            models.Like.objects.create(usuario=self.request.user, post=post)
            return redirect('post:detail', slug)

class sobre_mi(generic.TemplateView):
    """Vista sobre_mi"""
    template_name = 'post/sobremi.html'
        

src/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/6bfc8ebd07.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <div class="header">
            <h2>Proyecto blog Juan Castro</h2>
        </div>
        {% include "header.html" %}
    </header>
    <article>
        {% block content %}
      
        {% endblock content %}
    </article>
    <footer>
        {% include "footer.html" %}
    </footer>
</body>
</html>

src/templates/footer.html
<footer>
    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <span class="text-muted">&copy; 2022 Proyectos Basic Juan Castro</span>
            </div>
            <a href="#" class="btn btn-outline-primary me-2">Contactanos</a>
            </ul>
        </footer>
    </div>
</footer>

src/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'post:home' %}">Inicio
              <span class="visually-hidden">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'post:createpost' %}">Nuevo Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'post:sobremi' %}">Sobre mi</a>
          </li>
        </ul>
        {% if request.user.is_authenticated %}
        <a class="nav-link my-2 my-sm-0 active" href="{% url 'logout' %}">Cerrar Sesion</a>
        {% else %}
        <a class="nav-link my-2 my-sm-0 active" href="{% url 'login' %}">Iniciar Sesión</a>
        <a class="nav-link my-2 my-sm-0 active" href="{% url 'post:nuevousuario' %}">Registrar</a>
        {% endif %}
      </div>
    </div>
  </nav>

src/templates/post/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}{% endblock title %}

{% block content %}

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <h1>Esta seguro de eliminar este post: {{ object.title }}</h1>
    <input type="submit" value="Si. Estoy seguro">
</form>
<a href="{% url 'post:home' %}">volver</a>
{% endblock content %}

src/templates/post/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ title_pg }}{% endblock title %}

{% block content %}
<div class="card mb-3" style="padding: 50px;">
    <h3 class="card-header">{{ object.title }}</h3>
    <div class="text-center">
        <img src="{{ object.thumbnail.url }}" class="img-fluid" alt="...">
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ object.title }}</h5>
        <hr>
        <h6 class="card-subtitle text-muted">{{ object.content }}</h6>
    </div>
    <ul>
        <p class="list-group-item text-center">
            <span><a href="{{ object.get_like_url }}" class="btn btn-outline-dark">Like</a> <i
                    class="fa-solid fa-thumbs-up"></i> {{ object.get_like_count }} |</span>
            <span>Vistas <i class="fa-solid fa-eye"></i> {{ object.get_view_count }} |</span>
            <span>Comentarios <i class="fa-solid fa-comment"></i> {{ object.get_comment_count }} </span>
        </p>
        <div class="card-body">
            <a class="btn btn-primary" href="{% url 'post:home' %}">Volver</a>
            {% if request.user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'post:updatepost' object.id%}">Editar piblicacion</a>
            {% endif %}
        </div>
        <div class="card-footer text-muted">
            <small>Creado por: {{ object.autor }} - </small>
            {{ object.publish_date|timesince }}
        </div>
        <h3>Comentarios <i class="fa-solid fa-comment"></i></h3>
        {% for comment in object.comment %}
        <div class="toast show" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <strong class="me-auto">{{ comment.usuario }}</strong>
                <small>{{ comment.timestamp|timesince }}</small>
                <button type="button" class="btn-close ms-2 mb-1" data-bs-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
            </div>
            <div class="toast-body">
                {{ comment.coment }}
            </div>
        </div>
        {% endfor %}
        <h3>Comentar <i class="fa-solid fa-comment"></i></h3>
        {% if request.user.is_authenticated %}
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="{{ button }}">
        </form>
        {% else %}
        <a class="btn btn-primary" href="{% url 'login' %}">Iniciar Sesión</a>
        <a class="btn btn-primary" href="{% url 'post:nuevousuario' %}">Registrar</a>
        {% endif %}
    </ul>
</div>
{% endblock content %}

src/templates/post/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ view_type }}{% endblock title %}

{% block content %}
<div class="contenedor">
    {% if request.user.is_authenticated %}
    <h1>{{ view_type }} el post</h1>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="{{ view_type }}">
    </form>
    {% else %}
        <a class="btn btn-primary" href="{% url 'login' %}">Iniciar Sesión</a>
        <a class="btn btn-primary" href="{% url 'post:nuevousuario' %}">Registrar</a>
    {% endif %}
</div>
<a class="btn btn-primary" href="{% url 'post:home' %}">volver</a>
{% endblock content %}

src/templates/post/post_list.html
{% extends "base.html" %}

{% block title %}{{ title_pg }}{% endblock title %}

{% block content %}
<br>
<ul>
    <div class="row">
    {% for object in object_list %}
        <div class="col-2">
            <div class="card" style="width: 18rem;">
                <a href="{{ object.get_absolute_url }}">
                <img src="{{ object.thumbnail.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                </a>
                <p class="card-text">{{ object.content }}</p>
                <a href="{{ object.get_absolute_url }}" class="btn btn-primary">Ver Post</a>
                <p class="card-text">{{ object.publish_date|timesince }}</p>
                </div>
                <hr>
                <p class="text-center">
                    <span><i class="fa-solid fa-thumbs-up"></i> {{ object.get_like_count }} </span>
                    <span><i class="fa-solid fa-eye"></i> {{ object.get_view_count }} </span>
                    <span><i class="fa-solid fa-comment"></i> {{ object.get_comment_count }} </span>
                </p>
            </div>
        </div>
    {% endfor %}
    </div>
</ul>
<a class="btn btn-primary" href="{% url 'post:createpost' %}">nuevo post</a>
{% endblock content %}

src/templates/post/sobremi.html
{% extends 'base.html' %}

{% block title %}Sobre mi{% endblock title %}

{% block content %}
<div class="contenedor fst-italic">
    <h2>Informacion</h2>
    <h3>Este proyecto se realizo como practica de aprendizaje de las herramientas que proporciona Django. En este proyecto podras:</h3>
    <div>
        <li>Crear, editar y eliminar un Post</li>
        <li>Crear un usuario</li>
        <li>Crear un comentario para los Post (solo si estas reguistrado)</li>
        <li>Hacer un Like para los Post (solo si estas reguistrado)</li>
        <li>Se regista la cantidad de visualizaciones del post (solo si ya hizo login)</li>
    </div>
    <a style="color: white;" href="https://www.linkedin.com/in/juan-castro-18229ba7/">Mi Linkedin</a>
    <h2>Saludos</h2>
</div>
{% endblock content %}

src/templates/registro.html
{% extends 'base.html' %}

{% block title %} {% endblock%}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="form-group contenedor">
        <h2>Nuevo Usuario</h2>
        <div class="form-floating mb-3">
            <input class="form-control" id="username" name='username'/>
            <label for="username">User ID</label>
        </div>
        <div class="form-floating mb-3">
            <input type="email" class="form-control" id="email" name="email"/>
            <label for="email">Email address</label>
        </div>
        <div class="form-floating mb-3">
            <input type="password" class="form-control" id="password1" name="password1" />
            <label for="password1">Password</label>
        </div>
        <div class="form-floating mb-3">
            <input type="password" class="form-control" id="password2" name="password2" />
            <label for="password2">Confirmar Password</label>
        </div>
        <div class="d-grid gap-2">
            <button class="btn btn-lg btn-primary" type="submit">Crear Usuario</button>
            <a class="btn btn-primary" href="{% url 'login' %}" role="button">Volver</a>
        </div>
    </div>
</form>
{% endblock content %}